name: hello-world-actions
run-name: This is branch ${{ github.ref_name }} is Hello World
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: node -v
  deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to stage dev
